### ISSUE TITLE
URGENT: No PCB

### ISSUE THREAD

**Issue by AdinAck** [ECE-196/pcbassignment-team-5#1]
Hey Team 5,

The `export.zip` file you provided us does not contain any PCB design files (it has some drill files).

This would have been ok but when I looked in your KiCAD project it was empty, so I don't have a lot to work with here.

Please export the proper design files (a video showing how to do this is on Canvas and on the PCBWalkthrough repository).

**Comment by jundy2** [comment]
Hi Adin,

We followed the steps in the video, but we only get the gbr and drl files found in the export file. We have uploaded our Kicad project up to github. 

Best,
Ryan

**Comment by AdinAck** [comment]
Thanks!
